- name: Create user with ssh key
  hosts: all
  become: true
  vars:
    new_user: user1
  tasks:
    - name: Create user
      user:
        name: "{{ new_user }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        password: "{{ 'test123' | password_hash('sha512') }}"

    - name: Add SSH key
      authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
